### ISSUE TITLE
Catalina 10.15.6

### ISSUE THREAD

**Issue by fratnike** [IdlePhysicist/homebrew-caving#4] opened 2020-08-12 15:35 UTC
Dear @IdlePhysicist,

   thank you for your help, unfortunately also with your installation the problem persist... see attached logs.

best  regards

enrico
[therion_install_log2.txt](https://github.com/IdlePhysicist/homebrew-caving/files/5063772/therion_install_log2.txt)

**Comment by IdlePhysicist** [comment] 2020-08-12 15:58
So briefly looking at that, it failed due to tests not passing. A new error is always progress when trying to compile code from source! 

I also notice these errors further up in the logs
```
sh: cavern: command not found
sh: pdfetex: command not found
sh: pdfetex: command not found
```
The cavern one is new to me (cavern is part of the [Survex](https://survex.com) program), but I noted the `pdfetex` issue in #3. I have yet to find the time to track this down. To ensure that the `pdfetex` issue is the same one I noted, and not that you simply do not have it installed, can you please enter the following command into your terminal and return the output to me?
```
which pdfetex
```
If you see something like "command not found", then please install mactex with `brew cask install mactex`, and try to install Therion once again.


I would also like to note that in your issue in therion/therion#262 you were building from the master branch of Therion and not v5.5.0 as you did with my formula. To build the master branch with my formula please use `brew install --verbose --HEAD idlephysicist/caving/therion`

**Comment by fratnike** [comment] 2020-08-12 16:50
enricof@icts-enrico ~ % which pdfetex
/Library/TeX/texbin/pdfetex
enricof@icts-enrico ~ % 

Attached the 3rd log :(

Thank you again for all...
[therion_install_log3.txt](https://github.com/IdlePhysicist/homebrew-caving/files/5064338/therion_install_log3.txt)

**Comment by IdlePhysicist** [comment] 2020-08-12 16:57
Ok your latest log looks exactly as mine did for #3. I am having a look at this right now, the issue is that this line is not doing its job, and as such Homebrew cannot find `pdftex` or `pdfetex`.
https://github.com/IdlePhysicist/homebrew-caving/blob/964b1b7ee403de80a1d96a2237692ab64979dada/therion.rb#L28

**Comment by IdlePhysicist** [comment] 2020-08-12 17:27
I was able to install the HEAD version of Therion with this command:
```
brew install --env=std --verbose --HEAD idlephysicist/caving/therion
```

**Comment by IdlePhysicist** [comment] 2020-08-12 17:47
Closed by ca3c146
Incorrectly mentioned issue 2 instead of 4 in commit message.

**Closed as completed by IdlePhysicist** 2020-08-12 17:47 UTC

**Comment by fratnike** [comment] 2020-08-12 18:07
> I was able to install the HEAD version of Therion with this command:
> 
> ```
> brew install --env=std --verbose --HEAD idlephysicist/caving/therion
> ```

:(
[therion_install_log4.txt](https://github.com/IdlePhysicist/homebrew-caving/files/5064815/therion_install_log4.txt)

**Comment by IdlePhysicist** [comment] 2020-08-12 19:14
That is most definitely an issue to discuss with the Therion developers.
